# Generated by Django 3.1.5 on 2021-05-08 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_activewatchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='listingid',
        ),
    ]
