# Generated by Django 3.1.5 on 2021-05-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_remove_bid_listingid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='listingid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activewatchlist',
            name='listingid',
            field=models.IntegerField(default='', editable=False),
        ),
    ]
