# Generated by Django 3.1.5 on 2021-05-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20210510_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='title',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
