# Generated by Django 3.1.5 on 2021-05-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20210510_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activewatchlist',
            name='listingid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
