# Generated by Django 3.1.5 on 2021-05-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20210510_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='activewatchlist',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
