# Generated by Django 3.1.5 on 2021-05-11 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_activewatchlist_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activewatchlist',
            name='title',
        ),
    ]
