# Generated by Django 3.1.5 on 2021-05-11 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_remove_activewatchlist_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='title',
        ),
    ]
