# Generated by Django 3.1.5 on 2021-05-18 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_listing_is_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='is_closed',
        ),
    ]
