# Generated by Django 3.1.5 on 2021-05-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_auto_20210518_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listingid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
