# Generated by Django 3.1.5 on 2021-05-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_auto_20210518_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.CharField(max_length=1000)),
                ('winner', models.CharField(max_length=64)),
                ('listingid', models.IntegerField()),
                ('winbid', models.IntegerField()),
                ('title', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
