# Generated by Django 3.1.5 on 2021-05-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='title',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
