# Generated by Django 3.1.5 on 2021-05-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0028_bid_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='newbid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
