# Generated by Django 3.1.5 on 2021-05-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0030_auto_20210524_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
