# Generated by Django 3.1.5 on 2021-05-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0031_auto_20210524_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='newbid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
