# Generated by Django 3.1.5 on 2021-05-25 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0033_auto_20210525_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='newbid',
        ),
    ]
