# Generated by Django 3.1.5 on 2021-05-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0034_remove_listing_newbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='newbid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='listing',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='user',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
