# Generated by Django 3.1.5 on 2021-05-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0036_auto_20210525_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='newbid',
            field=models.IntegerField(),
        ),
    ]
