# Generated by Django 3.1.5 on 2021-05-27 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0038_remove_listing_newbid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='user',
        ),
    ]
