# Generated by Django 3.1.5 on 2021-05-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0039_remove_bid_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='user',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
