# Generated by Django 3.1.5 on 2021-05-27 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='user',
            new_name='userr',
        ),
    ]
