# Generated by Django 3.1.5 on 2021-05-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_remove_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='newbid',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
