# Generated by Django 3.1.5 on 2021-05-27 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_listing_newbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bid',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
    ]
