# Generated by Django 3.1.5 on 2021-06-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_listing_newbiduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
    ]
