# Generated by Django 3.1.5 on 2021-06-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listing_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='winner',
            name='listingid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='winner',
            name='winbid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
