# Generated by Django 3.1.5 on 2021-06-05 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210603_1227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Winner',
        ),
    ]
