# Generated by Django 3.1.5 on 2021-06-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_delete_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='newbiduser',
            field=models.CharField(blank=True, default=None, max_length=1000),
        ),
    ]
