# Generated by Django 3.1.5 on 2021-06-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20210608_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='newbid',
            field=models.IntegerField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='newbiduser',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
