# Generated by Django 3.1.5 on 2021-06-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20210608_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='newbid',
            field=models.IntegerField(blank=True),
        ),
    ]
