# Generated by Django 3.1.5 on 2021-06-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20210608_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='newbid',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
