# Generated by Django 3.1.5 on 2021-06-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20210608_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='activewatchlist',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='activewatchlist',
            name='image_link',
            field=models.CharField(blank=True, default=None, max_length=5000000, null=True),
        ),
        migrations.AddField(
            model_name='activewatchlist',
            name='starting_bid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activewatchlist',
            name='user',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
