# Generated by Django 3.1.5 on 2021-06-08 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_auto_20210608_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activewatchlist',
            name='created_time',
        ),
        migrations.RemoveField(
            model_name='activewatchlist',
            name='image_link',
        ),
        migrations.RemoveField(
            model_name='activewatchlist',
            name='starting_bid',
        ),
    ]
